# Generated by Django 6.0.1 on 2026-01-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title displayed in portfolio', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (auto-generated from title)', unique=True)),
                ('short_description', models.CharField(help_text='Brief one-liner or summary of the project', max_length=300)),
                ('description', models.TextField(help_text='Detailed project description with context, challenges, and outcomes')),
                ('tech_stack', models.TextField(help_text='Comma-separated list of technologies (e.g., Django, React, PostgreSQL)')),
                ('thumbnail', models.ImageField(blank=True, help_text='Project thumbnail or preview image', null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True, help_text='Link to GitHub repository', null=True)),
                ('live_url', models.URLField(blank=True, help_text='Link to live project or demo', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Display this project prominently on homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual ordering position (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-is_featured', 'order', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='pages_proje_slug_05948e_idx'), models.Index(fields=['is_featured', 'order'], name='pages_proje_is_feat_bc1702_idx')],
            },
        ),
    ]
