# Generated by Django 6.0.1 on 2026-01-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Sender's name", max_length=200)),
                ('email', models.EmailField(help_text="Sender's email address", max_length=254)),
                ('phone', models.CharField(blank=True, help_text="Sender's phone number (optional)", max_length=20)),
                ('subject', models.CharField(help_text='Message subject or topic', max_length=300)),
                ('message', models.TextField(help_text='Message content')),
                ('is_read', models.BooleanField(default=False, help_text='Mark whether this message has been read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='pages_conta_created_f62b22_idx'), models.Index(fields=['is_read'], name='pages_conta_is_read_e22010_idx')],
            },
        ),
    ]
